# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

install: true

script: mvn clean package -DskipTests=true

jdk:
  - openjdk11

services:
  - postgresql

env:
  global:
    - CODECOV_TOKEN="aa041aef-e23d-4e99-99f7-c6fd73ef07c1"

before_install:
  - psql -c 'create database forum;' -U postgres

cache:
  directories:
    - $HOME/.m2

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - hedg.r52@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

deploy:
  provider: heroku
  api_key:
    secure: MBV3ov4wYHsA+qRuHGfMYJxGLeZ5QpdHMWEXtr6cDsmKYiK0iWvhtsQbu/nELaIro/cuWFsMevCGoS+iMtqxxdkmIVGA0bj2xw60enAyH37zr1bCmZQoRwHo9woaxe6z6Ba3bguqKLbaTCbFxclLkau6lVLVLwqU4qIYFNZRVoA+SDzOdJTqnmnAgExzYCGqVWOxufjTvw8Q+u7nm6NvnpGnWzrKXtNWqWJS99idI1uep4zqhre7NprQ9qZMBOEzHjK3JNrphThfZ6P1USwhjBOZKhgfG+BVdHiHOVvQZu11JpPyO5x4VMRPtsNiecrQriBoE74JVTc/7Ur/qyh94ngMCd1xSsxSjvt17Ii/Y0NEYH/7DXnTdjFwi0vTkkdfFjw+VPTRqdPqZecfWI/BIGihupxGTY2D5Vj1AERLeUMz5W9hOShNRUV1GHU+XvmkaJATAHM7Wrrg9fJ2IAeodvDNqzqXQajF7GCOE9J4eFsTX4kFV4aXjZ6OHKSGULW/ABIBy7M9CySz7e3sijnYWwGb+BD7hkEX+BssDTvcXNS5iNpmOUqJ+x8AUK9xvHLBW0+V+uX5b3Sf07JSzclicrf3FRMHZmiJxbHT88S+E+bSXEqaFeWRiZE2S4+ikpx81Iw+0TCcASBajPYY66RZO9IdRYBqJtRZoMlg7lyRNk4=
  app: desolate-fortress-67168