# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

jdk:
  - openjdk11

services:
#  - postgresql

env:
  global:
    - CODECOV_TOKEN="aa041aef-e23d-4e99-99f7-c6fd73ef07c1"

before_install:
#  - psql -c 'create database tracker;' -U postgres

cache:
  directories:
    - $HOME/.m2

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - hedg.r52@gmail.com
    on_success: never # default: change
    on_failure: always # default: always